development:
  secret_key_base: 59c6f1e1e7ff437eec006faf5af689e9914d5a57492db7d34c0f583549dc032a6fe1948d3e79d125bb93f86f4e3f83defd41dc200afa29ee38e8b52e3aa69e0a
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
test:
  secret_key_base: 59c6f1e1e7ff437eec006faf5af689e9914d5a57492db7d34c0f583549dc032a6fe1948d3e79d125bb93f86f4e3f83defd41dc200afa29ee38e8b52e3aa69e0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KET"] %>